---
title: "rawRNA_analysis"
author: "Nikolai Egorov, Mingxuan Fan, Zhixin Mao"
date: "2025-06-20"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
packages <- c("data.table", "readxl", "DESeq2")
installed <- packages %in% rownames(installed.packages())
if (any(!installed)) {
  install.packages(packages[!installed])
}
# Bioconductor packages like DESeq2 may need BiocManager
if (!requireNamespace("DESeq2", quietly = TRUE)) {
  if (!requireNamespace("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager")
  }
  BiocManager::install("DESeq2")
}

library(data.table)
library(readxl)
library(DESeq2)
```

```{r}
file_path <- "data/transneo-diagnosis-RNAseq-rawcounts.tsv.gz"
# Use fread from data.table for fast reading of gzipped tab-separated files
df <- fread(file_path, header = TRUE, sep = "\t", data.table = FALSE)
```

```{r}
# Inspect
first6_genes <- head(df)
print(first6_genes)
```

```{r}
metadata <- data.frame(read_excel("data/Supplementary_table.xlsx", sheet = 1))
# Perform analyses with cases that had an RCB assessment and received more than one cycle of therapy
# as detailed in Methods (Statistical testing)
metadata <- metadata[metadata$RCB.category!="NA",]
metadata <- metadata[metadata$Chemo.cycles>1 & metadata$aHER2.cycles>1,]
head(metadata)
```

```{r}
samples_count <- colnames(df)[-1]
samples_meta <- metadata$Donor.ID

# find the common IDs
#common      <- intersect(samples_count, samples_meta)
#length(common)   # how many samples remain

#countData <- df[, common, drop=FALSE]

# if your rownames(meta) are sample IDs:
#colData   <- metadata[match(common, metadata$Donor.ID), , drop=FALSE]
#head(colData)
```

```{r}
# Create a binary “response” column
metadata$response <- ifelse(metadata$RCB.category == "pCR", "pCR", "RD")
# When build colData, it will carry that column through:
common   <- intersect(colnames(df)[-1], metadata$Donor.ID)
countData <- df[, common, drop=FALSE]
colData   <- metadata[match(common, metadata$Donor.ID), , drop=FALSE]

# Inspect
head(colData[, c("RCB.category","response")])
```

```{r}
# Differential expression with DESeq2
# Input: un-normalized counts
dds <- DESeqDataSetFromMatrix(
  countData = countData,
  colData   = colData,
  design    = ~ response
)

# pre‐filter: drop genes with very low counts across all samples
#keep <- rowSums(counts(dds) >= 10) >= 3
#dds  <- dds[keep, ]

# Run DESeq
dds <- DESeq(dds)
```

```{r}
# Check what you can test
resultsNames(dds)

res <- results(dds, contrast=c("response","pCR","no pCR"))
summary(res)
```

```{r}

```